// angular/src/app/staff/new-employee-form/new-employee-form.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { StaffService } from '../staff.service';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { Employee, EmployeeGroup } from '../staff.model';
@Component({
  selector: 'app-new-employee-form',
  templateUrl: './new-employee-form.component.html',
  styleUrls: ['./new-employee-form.component.scss'],
})
export class NewEmployeeFormComponent implements OnInit {
  firstName: string;
  lastName: string;
  group: EmployeeGroup;
  groupOptions = [
    { label: 'Admin', value: 'admin' },
    { label: 'Doctor', value: 'doctor' },
    { label: 'Nurse', value: 'nurse' },
  ];

  constructor(
    private staffService: StaffService,
    public dialogRef: MatDialogRef<NewEmployeeFormComponent>,
    @Inject(MAT_DIALOG_DATA) public data: Employee
  ) {}

  ngOnInit(): void {}

  create() {
    this.staffService.addEmployee({
      id: new Date().getTime(),
      firstName: this.firstName,
      lastName: this.lastName,
      group: this.group,
    });

    this.dialogRef.close();
  }

  cancel() {
    this.dialogRef.close();
  }

  // TODO: add validation!!!
}

<div class="app-new-employee-form">
  <h3>Add Employee</h3>

  <mat-form-field>
    <mat-label>First Name*</mat-label>
    <input matInput type="text" [(ngModel)]="firstName" />
  </mat-form-field>

  <br />

  <mat-form-field>
    <mat-label>Last Name*</mat-label>

    <input matInput type="text" [(ngModel)]="lastName" />
  </mat-form-field>

  <br />

  <mat-form-field>
    <mat-label>Group*</mat-label>

    <mat-select [(ngModel)]="group">
      <mat-option
        *ngFor="let groupOption of groupOptions"
        [value]="groupOption.value"
      >
        {{ groupOption.label }}
      </mat-option>
    </mat-select>
  </mat-form-field>

  <br />

  <button
    mat-raised-button
    color="primary"
    (click)="create()"
    [disabled]="!firstName || !lastName || !group"
  >
    Create
  </button>
  <button mat-raised-button (click)="cancel()">Cancel</button>
</div>

// react/src/components/Staff/NewEmployeeForm/NewEmployeeForm.jsx
import React from "react";
import "./NewEmployeeForm.scss";
import { bindActionCreators } from "redux";
import * as staffActions from "../../../redux/actions/staffActions";
import { connect } from "react-redux";
import { useState } from "react";

function NewEmployeeForm({ actions, hideModal }) {
  let groupOption = [
    { label: "Admin", value: "admin" },
    { label: "Doctor", value: "doctor" },
    { label: "Nurse", value: "nurse" },
  ];

  let options = groupOption.map((el, i) => (
    <option key={i} value={el.value}>
      {el.label}
    </option>
  ));

  let getNewEmployee = () => {
    return {
      id: new Date().getTime(),
      firstName,
      lastName,
      group,
    };
  };

  const [{ firstName, lastName, group }, setInput] = useState("");

  return (
    <div className="app-new-employee-form">
      <h3>Add Employee</h3>

      <label>First Name *</label>
      <input
        value={firstName || ""}
        type="text"
        className="form-control"
        onChange={(e) => {
          setInput({ firstName: e.target.value, lastName, group });
        }}
      />

      <br />

      <label>Last Name *</label>

      <input
        value={lastName || ""}
        type="text"
        className="form-control"
        onChange={(e) => {
          setInput({ firstName, lastName: e.target.value, group });
        }}
      />

      <br />

      <label>Group *</label>

      <select
        className="form-control"
        value={group || ""}
        onChange={(e) => {
          setInput({ firstName, lastName, group: e.target.value });
        }}
      >
        <option value></option>
        {options}
      </select>

      <br />

      {!firstName || !lastName || !group ? (
        <button className="btn btn-primary m-2" disabled>
          Create
        </button>
      ) : (
        <button
          className="btn btn-primary m-2"
          onClick={() => {
            actions.addEmployee(getNewEmployee());
            hideModal();
          }}
        >
          Create
        </button>
      )}

      <button className="btn btn-danger m-2" onClick={hideModal}>
        Cancel
      </button>
    </div>
  );
}

function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators(
      {
        ...staffActions,
      },
      dispatch
    ),
  };
}

export default connect(null, mapDispatchToProps)(NewEmployeeForm);
